# Site information
site_name: Mark Olson's Tutorial Repository

## To DO - Creative Commons and Google Analytics

# Copyright
# copyright: '<a href="#">Copyright</a> &copy; 2016 - 2017 Martin Donath'

# Google Analytics
# google_analytics:
#  - 'UA-XXXXXXXX-X'
#  - 'auto'

# Material for MkDocs Theme Configuration
theme:
  name: 'material'
  custom_dir: 'theme'
  palette:
    primary: 'white'
    accent: 'indigo'
  logo: 'images/avatar.svg'
  favicon: 'images/favicon.ico'

extra_css:
  - 'stylesheets/extra.css'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - pymdownx.arithmatex
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true

# Extra Javascript
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

# Page Hierarchy for Nav / TOC
nav:
  - 'index.md'
  - Circuits:
    - 'Tinkercad' : 'circuits/tinkercad/index.md'
    - 'ATtiny85' : 'circuits/attiny85/index.md'
    - 'Feather M0' : 'circuits/feather/index.md'
    - 'Blynk' : 'circuits/blynk/index.md'
    - 'MQTT' : 'circuits/mqtt/index.md'
    - 'Instagram API' : 'circuits/instagram/index.md'
    - 'Twitter API' : 'circuits/twitter/index.md'
  - 'Machine Learning':
    - 'PyTorch DCGAN' : 'machine-learning/pytorch-dcgan/index.md'


